[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hsort"
version = "1.3.3"
description = "A high-performance sorting and merging engine optimized for processing large-scale data files, with stable multi-key sorting support for fixed-length, variable-length, and CSV formats."
readme = "README.md"

[project.urls]
Homepage = "hhttps://github.com/xuhui-hou/hsort"
Repository = "https://github.com/xuhui-hou/hsort"
Issues = "https://github.com/xuhui-hou/hsort/issues"

